//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDRaidToolDataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int EID { get; set; }
        public int PlayerID { get; set; }
        public int ProfessionID { get; set; }
        public int SpecializationID { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> Pref { get; set; }
    }
}
